import Header from "@/components/custom/header";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import StoreProvider from "./providers/StoreProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`${manrope.variable} antialiased`}>
          <Header />
          <main className="container mx-auto flex items-center justify-between px-24 py-6">
            {children}
          </main>
          <Toaster richColors />
        </body>
      </StoreProvider>
    </html>
  );
}
