import Header from "@/components/custom/header";
import Refresher from "@/components/custom/refresher";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/lib/providers/QueryProvider";
import StoreProvider from "@/lib/providers/StoreProvider";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
	variable: "--font-manrope",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<StoreProvider>
				<body className={`${manrope.variable} antialiased`}>
					<QueryProvider>
						<Refresher>
							<main className="container mx-auto flex flex-col items-center justify-between">
								{children}
							</main>
						</Refresher>
					</QueryProvider>
					<Toaster richColors />
				</body>
			</StoreProvider>
		</html>
	);
}
